version: '3.8'
services:
  rasa:
    build: .
    volumes:
      - .:/app
    ports:
      - "5005:5005"
    depends_on:
      - duckling
      - backend
      - db
      - frontend
    environment:
      - DATABASE_URL=postgresql://vanderson:senha@db:5432/chatbot
  
    
    
  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"

  backend:
    build: ../backend-chat
    ports:
      - "3010:3010"
    volumes:
      - ../backend-chat:/app
    environment:
      - NODE_ENV=production
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=vanderson
      - PG_PASSWORD=senha
      - PG_DATABASE=chatbot
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
    ports:
      - "3001:3001"
    volumes:
      - ../frontend:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: vanderson
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  action-server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions

volumes:
  postgres-data:
